services:
  - type: web
    name: servistakip-app-unified
    env: node
    buildCommand: npm run render-build
    startCommand: npm start
    branch: main
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: servistakip-db
          property: connectionString
      - key: NODE_VERSION
        value: 20.11.0
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 5000
